import { extendTailwindMerge } from "tailwind-merge";

export const twMerge = extendTailwindMerge({
  extend: {
    classGroups: {
      "font-size": [
        "text-h1",
        "text-h3",
        "text-body-1",
        "text-body-2",
        "text-body-3",
        "text-body-4",
      ],
      rounded: ["rounded-10"],
      "text-color": [
        "text-gray-3",
        "text-gray-2",
        "text-gray-1",
        "text-gray-light",
        "text-dark-blue",
        "text-dark",
        "text-black",
        "text-text-black",
        "text-red",
        "text-accent",
        "text-accent-light",
        "text-gray-dark",
        "text-gray-icon",
        "text-white",
      ],
      "bg-color": [
        "bg-gray-3",
        "bg-gray-2",
        "bg-gray-1",
        "bg-gray-light",
        "bg-dark-blue",
        "bg-dark",
        "bg-black",
        "bg-red",
        "bg-page",
        "bg-bg-page",
        "bg-white",
        "bg-bg-white",
        "bg-accent",
        "bg-accent-light",
        "bg-gray-dark",
        "bg-gray-bg",
        "bg-gray-icon",
      ],
      "border-color": [
        "border-gray-3",
        "border-gray-2",
        "border-gray-1",
        "border-gray-light",
        "border-dark-blue",
        "border-dark",
        "border-black",
        "border-red",
        "border-accent",
        "border-accent-light",
        "border-gray-dark",
        "border-gray-icon",
      ],
    },
  },
});
